function(add_broseat_test name)
    add_executable(${name} ${name}.cpp)
    target_link_libraries(${name} PRIVATE broseat::broseat)
    target_include_directories(${name} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../src)
    broseat_warnings(${name})
    add_test(NAME ${name} COMMAND ${name})
    set_tests_properties(${name} PROPERTIES SKIP_RETURN_CODE 77)
endfunction()

add_broseat_test(test_types)
add_broseat_test(test_event_queue)
add_broseat_test(test_seat)
add_broseat_test(test_session)
add_broseat_test(test_autostart)
add_broseat_test(test_idle_inhibit)
add_broseat_test(test_dbus)
